package db

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Record) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "rr":
			z.RR, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RR")
				return
			}
		case "expires":
			z.Expires, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Expires")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Record) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "rr"
	err = en.Append(0x82, 0xa2, 0x72, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.RR)
	if err != nil {
		err = msgp.WrapError(err, "RR")
		return
	}
	// write "expires"
	err = en.Append(0xa7, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Expires)
	if err != nil {
		err = msgp.WrapError(err, "Expires")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Record) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "rr"
	o = append(o, 0x82, 0xa2, 0x72, 0x72)
	o = msgp.AppendString(o, z.RR)
	// string "expires"
	o = append(o, 0xa7, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73)
	o = msgp.AppendInt64(o, z.Expires)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Record) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "rr":
			z.RR, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RR")
				return
			}
		case "expires":
			z.Expires, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Expires")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Record) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.RR) + 8 + msgp.Int64Size
	return
}
